
-- PROJETO DE CURRICULARIZAÇÃO - BANCO DE DADOS DE REVENDA
-- DDL COM SEQUENCES E TRIGGERS 

-- 1. TABELAS CADASTRAIS (INDEPENDENTES)



-- TABELA: FORNECEDORES

CREATE TABLE FORNECEDORES (
    for_id       NUMBER(5)     NOT NULL,
    for_nome     VARCHAR2(150) NOT NULL,
    for_telefone VARCHAR2(20),
    CONSTRAINT pk_fornecedores PRIMARY KEY (for_id)
);

CREATE SEQUENCE FORNECEDORES_FOR_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER FORNECEDORES_FOR_ID_TRG
BEFORE INSERT ON FORNECEDORES
FOR EACH ROW
BEGIN
    :NEW.for_id := FORNECEDORES_FOR_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: MARCAS

CREATE TABLE MARCAS (
    mar_id   NUMBER(5)     NOT NULL,
    mar_nome VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_marcas PRIMARY KEY (mar_id)
);

CREATE SEQUENCE MARCAS_MAR_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER MARCAS_MAR_ID_TRG
BEFORE INSERT ON MARCAS
FOR EACH ROW
BEGIN
    :NEW.mar_id := MARCAS_MAR_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: CATEGORIAS

CREATE TABLE CATEGORIAS (
    cat_id   NUMBER(5)     NOT NULL,
    cat_nome VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (cat_id)
);

CREATE SEQUENCE CATEGORIAS_CAT_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER CATEGORIAS_CAT_ID_TRG
BEFORE INSERT ON CATEGORIAS
FOR EACH ROW
BEGIN
    :NEW.cat_id := CATEGORIAS_CAT_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: CLIENTES

CREATE TABLE CLIENTES (
    cli_id       NUMBER(5)     NOT NULL,
    cli_nome     VARCHAR2(150) NOT NULL,
    cli_telefone VARCHAR2(20),
    CONSTRAINT pk_clientes PRIMARY KEY (cli_id)
);

CREATE SEQUENCE CLIENTES_CLI_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER CLIENTES_CLI_ID_TRG
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
    :NEW.cli_id := CLIENTES_CLI_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: TIPO_IDENTIFICADOR

CREATE TABLE TIPO_IDENTIFICADOR (
    tid_id        NUMBER(5)     NOT NULL,
    tid_nome      VARCHAR2(50)  NOT NULL,
    tid_descricao VARCHAR2(255),
    CONSTRAINT pk_tipo_identificador PRIMARY KEY (tid_id)
);

CREATE SEQUENCE TIPO_IDENTIFICADOR_TID_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER TIPO_IDENTIFICADOR_TID_ID_TRG
BEFORE INSERT ON TIPO_IDENTIFICADOR
FOR EACH ROW
BEGIN
    :NEW.tid_id := TIPO_IDENTIFICADOR_TID_ID_SEQ.NEXTVAL;
END;
/



-- 2. PRODUTOS (DEPENDENTE DE MARCAS E CATEGORIAS)


CREATE TABLE PRODUTOS (
    prod_id                NUMBER(5)     NOT NULL,
    prod_mar_id            NUMBER(5)     NOT NULL,
    prod_cat_id            NUMBER(5)     NOT NULL,
    prod_nome              VARCHAR2(150) NOT NULL,
    prod_preco_venda_atual NUMBER(10,2)  NOT NULL,
    CONSTRAINT pk_produtos PRIMARY KEY (prod_id),
    CONSTRAINT fk_prod_mar FOREIGN KEY (prod_mar_id) REFERENCES MARCAS(mar_id),
    CONSTRAINT fk_prod_cat FOREIGN KEY (prod_cat_id) REFERENCES CATEGORIAS(cat_id)
);

CREATE SEQUENCE PRODUTOS_PROD_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER PRODUTOS_PROD_ID_TRG
BEFORE INSERT ON PRODUTOS
FOR EACH ROW
BEGIN
    :NEW.prod_id := PRODUTOS_PROD_ID_SEQ.NEXTVAL;
END;
/



-- 3. ENTRADAS (COMPRAS, ITENS E RASTREABILIDADE)



-- TABELA: COMPRAS

CREATE TABLE COMPRAS (
    com_id          NUMBER(5) NOT NULL,
    com_for_id      NUMBER(5) NOT NULL,
    com_data_compra DATE      NOT NULL,
    CONSTRAINT pk_compras PRIMARY KEY (com_id),
    CONSTRAINT fk_com_for FOREIGN KEY (com_for_id) REFERENCES FORNECEDORES(for_id)
);

CREATE SEQUENCE COMPRAS_COM_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER COMPRAS_COM_ID_TRG
BEFORE INSERT ON COMPRAS
FOR EACH ROW
BEGIN
    :NEW.com_id := COMPRAS_COM_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: ITENS_COMPRA

CREATE TABLE ITENS_COMPRA (
    itc_id                    NUMBER(5)    NOT NULL,
    itc_com_id                NUMBER(5)    NOT NULL,
    itc_prod_id               NUMBER(5)    NOT NULL,
    itc_quantidade            INTEGER      NOT NULL,
    itc_valor_unitario_compra NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_itens_compra PRIMARY KEY (itc_id),
    CONSTRAINT fk_itc_com FOREIGN KEY (itc_com_id) REFERENCES COMPRAS(com_id),
    CONSTRAINT fk_itc_prod FOREIGN KEY (itc_prod_id) REFERENCES PRODUTOS(prod_id)
);

CREATE SEQUENCE ITENS_COMPRA_ITC_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER ITENS_COMPRA_ITC_ID_TRG
BEFORE INSERT ON ITENS_COMPRA
FOR EACH ROW
BEGIN
    :NEW.itc_id := ITENS_COMPRA_ITC_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: IDENTIFICADOR_ITEM

CREATE TABLE IDENTIFICADOR_ITEM (
    idi_id     NUMBER(5)     NOT NULL,
    idi_itc_id NUMBER(5)     NOT NULL,
    idi_tid_id NUMBER(5)     NOT NULL,
    idi_valor  VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_identificador_item PRIMARY KEY (idi_id),
    CONSTRAINT fk_idi_itc FOREIGN KEY (idi_itc_id) REFERENCES ITENS_COMPRA(itc_id),
    CONSTRAINT fk_idi_tid FOREIGN KEY (idi_tid_id) REFERENCES TIPO_IDENTIFICADOR(tid_id)
);

CREATE SEQUENCE IDENTIFICADOR_ITEM_IDI_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER IDENTIFICADOR_ITEM_IDI_ID_TRG
BEFORE INSERT ON IDENTIFICADOR_ITEM
FOR EACH ROW
BEGIN
    :NEW.idi_id := IDENTIFICADOR_ITEM_IDI_ID_SEQ.NEXTVAL;
END;
/



-- 4. SAÍDAS (VENDAS E ITENS VENDIDOS)



-- TABELA: VENDAS

CREATE TABLE VENDAS (
    ven_id         NUMBER(5) NOT NULL,
    ven_cli_id     NUMBER(5) NOT NULL,
    ven_data_venda DATE      NOT NULL,
    CONSTRAINT pk_vendas PRIMARY KEY (ven_id),
    CONSTRAINT fk_ven_cli FOREIGN KEY (ven_cli_id) REFERENCES CLIENTES(cli_id)
);

CREATE SEQUENCE VENDAS_VEN_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER VENDAS_VEN_ID_TRG
BEFORE INSERT ON VENDAS
FOR EACH ROW
BEGIN
    :NEW.ven_id := VENDAS_VEN_ID_SEQ.NEXTVAL;
END;
/


-- TABELA: ITENS_VENDA

CREATE TABLE ITENS_VENDA (
    itv_id                   NUMBER(5)    NOT NULL,
    itv_ven_id              NUMBER(5)    NOT NULL,
    itv_itc_id              NUMBER(5)    NOT NULL,
    itv_quantidade           INTEGER      NOT NULL,
    itv_valor_unitario_venda NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_itens_venda PRIMARY KEY (itv_id),
    CONSTRAINT fk_itv_ven FOREIGN KEY (itv_ven_id) REFERENCES VENDAS(ven_id),
    CONSTRAINT fk_itv_itc FOREIGN KEY (itv_itc_id) REFERENCES ITENS_COMPRA(itc_id)
);

CREATE SEQUENCE ITENS_VENDA_ITV_ID_SEQ
    START WITH 1
    NOCACHE
    ORDER;

CREATE OR REPLACE TRIGGER ITENS_VENDA_ITV_ID_TRG
BEFORE INSERT ON ITENS_VENDA
FOR EACH ROW
BEGIN
    :NEW.itv_id := ITENS_VENDA_ITV_ID_SEQ.NEXTVAL;
END;
/