-- DDL - BANCO DE DADOS DE VENDAS

CREATE TABLE FORNECEDORES (
    id_fornecedor INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome          VARCHAR2(150) NOT NULL,
    telefone      VARCHAR2(20),
    CONSTRAINT pk_fornecedores PRIMARY KEY (id_fornecedor)
);

CREATE TABLE MARCAS (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome     VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_marcas PRIMARY KEY (id_marca)
);

CREATE TABLE CATEGORIAS (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_categorias PRIMARY KEY (id_categoria)
);

CREATE TABLE CLIENTES (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome       VARCHAR2(150) NOT NULL,
    telefone   VARCHAR2(20),
    CONSTRAINT pk_clientes PRIMARY KEY (id_cliente)
);

CREATE TABLE PRODUTOS (
    id_produto        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_marca          INTEGER NOT NULL,
    id_categoria      INTEGER NOT NULL,
    nome              VARCHAR2(150) NOT NULL,
    preco_venda_atual NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_produtos PRIMARY KEY (id_produto),
    CONSTRAINT fk_produto_marca
        FOREIGN KEY (id_marca) REFERENCES MARCAS(id_marca),
    CONSTRAINT fk_produto_categoria
        FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS(id_categoria)
);

CREATE TABLE COMPRAS (
    id_compra     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_fornecedor INTEGER NOT NULL,
    data_compra   TIMESTAMP NOT NULL,

    CONSTRAINT pk_compras PRIMARY KEY (id_compra),
    CONSTRAINT fk_compra_fornecedor
        FOREIGN KEY (id_fornecedor) REFERENCES FORNECEDORES(id_fornecedor)
);

CREATE TABLE ITENS_COMPRA (
    id_item_compra        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_compra             INTEGER NOT NULL,
    id_produto            INTEGER NOT NULL,
    quantidade            INTEGER NOT NULL,
    valor_unitario_compra NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_itens_compra PRIMARY KEY (id_item_compra),
    CONSTRAINT fk_item_compra_compra
        FOREIGN KEY (id_compra) REFERENCES COMPRAS(id_compra),
    CONSTRAINT fk_item_compra_produto
        FOREIGN KEY (id_produto) REFERENCES PRODUTOS(id_produto)
);

CREATE TABLE VENDAS (
    id_venda   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente INTEGER NOT NULL,
    data_venda TIMESTAMP NOT NULL,

    CONSTRAINT pk_vendas PRIMARY KEY (id_venda),
    CONSTRAINT fk_venda_cliente
        FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);

CREATE TABLE ITENS_VENDA (
    id_item_venda        INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_venda             INTEGER NOT NULL,
    id_item_compra       INTEGER NOT NULL,
    quantidade            INTEGER NOT NULL,
    valor_unitario_venda NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_itens_venda PRIMARY KEY (id_item_venda),
    CONSTRAINT fk_item_venda_venda
        FOREIGN KEY (id_venda) REFERENCES VENDAS(id_venda),
    CONSTRAINT fk_item_venda_compra
        FOREIGN KEY (id_item_compra) REFERENCES ITENS_COMPRA(id_item_compra)
);

CREATE TABLE TIPO_IDENTIFICADOR (
    id_tipo_identificador INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nome                  VARCHAR2(50) NOT NULL,
    descricao             VARCHAR2(255),

    CONSTRAINT pk_tipo_identificador PRIMARY KEY (id_tipo_identificador)
);

CREATE TABLE IDENTIFICADOR_ITEM (
    id_identificador_item INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_item_compra        INTEGER NOT NULL,
    id_tipo_identificador INTEGER NOT NULL,
    valor                 VARCHAR2(100) NOT NULL,

    CONSTRAINT pk_identificador_item PRIMARY KEY (id_identificador_item),
    CONSTRAINT fk_ident_item_compra
        FOREIGN KEY (id_item_compra) REFERENCES ITENS_COMPRA(id_item_compra),
    CONSTRAINT fk_ident_item_tipo
        FOREIGN KEY (id_tipo_identificador) REFERENCES TIPO_IDENTIFICADOR(id_tipo_identificador)
);
